### PR TITLE
URGENT: Fixes compile time bug based on non-existent member

### PR DESCRIPTION
**Pull request by bcarlson-dev**
Fixes: 
```
/home/bcarlson/testing/OneWifi//source/core/wifi_ctrl_rbus_handlers.c:415:47: error: ‘wifi_preassoc_control_t’ has no member named ‘tcm_client_deny_assoc_info’; did you mean ‘client_deny_assoc_info’?
  415 |         strncpy(vap_info->u.bss_info.preassoc.tcm_client_deny_assoc_info, str,
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               client_deny_assoc_info
/home/bcarlson/testing/OneWifi//source/core/wifi_ctrl_rbus_handlers.c:416:50: error: ‘wifi_preassoc_control_t’ has no member named ‘tcm_client_deny_assoc_info’; did you mean ‘client_deny_assoc_info’?
  416 |             sizeof(vap_info->u.bss_info.preassoc.tcm_client_deny_assoc_info));
```

compile-time errors introduced in commit ec9235ccd55fce1c1f76dd804187a2582cab04c6

## To Replicate

```
mkdir testing && cd testing
git clone https://github.com/rdkcentral/OneWifi.git 
git clone https://github.com/rdkcentral/unified-wifi-mesh.git 
cd OneWifi && git checkout ec9235ccd55fce1c1f76dd804187a2582cab04c6
make -f build/linux/makefile setup
make -f build/linux/makefile all
```

@HarshavardhanP1

### CODE REVIEW

**Comment by bcarlson-dev** [comment]
Problematic commit ec9235ccd55fce1c1f76dd804187a2582cab04c6 has been reverted. Closing this PR.

**Comment by bcarlson-dev** [comment]
Problematic commit ec9235ccd55fce1c1f76dd804187a2582cab04c6 has been reverted. Closing this PR.
