### PR TITLE
RDKBACCL-1885 : observing BPI build issue in tip code of onewifi

### PR DESCRIPTION
**Pull request by kpandu987**
Reason for change: Observing below errors,
../../../git/source/webconfig/wifi_ovsdb_translator.c:3075:98: error: 'struct schema_Wifi_VIF_State' has no member named 'mld_if_name'; did you mean 'if_name'?       |  3075 |         if (get_mlo_vap_name_from_per_radio(vap->vap_name, vap_row->mld_if_name, sizeof(vap_row->mld_if_name))) {
which is caused by https://github.com/rdkcentral/OneWifi/pull/1158
Test Procedure: BPI build successful
Risks: None

### CODE REVIEW

**Comment by Nikita-Hakai** [comment]
Internal gerrit build: https://gerrit.teamccp.com/#/c/959480/ - Success

**Review by Nikita-Hakai — APPROVED** [review]

**Review by narendradandu — APPROVED** [review]
